### ISSUE TITLE
Repo name wrong in package.json

### ISSUE THREAD

**Issue by tedw** [strarsis/sass-math-pow#1]
Just noticed that the repo name is `eyeglass-sass-math-pow` in `package.json` instead of `sass-math-pow`

``` json
  "repository": "strarsis/eyeglass-sass-math-pow",
  "author": {
    "name": "strarsis",
    "email": "strarsis@gmail.com",
    "url": "https://github.com/strarsis/eyeglass-sass-math-pow"
  },
```

I tried to click the github link on npm and got a 404, which is why I noticed 😉

**Comment by strarsis** [comment]
Thanks for the remark.
Fixed in release v0.1.3.
